version: '3.4'

services:
  app:
    container_name: node-web-app
    build: .
    tty: true
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
volumes:
  node_modules: {}
